[commands]
start = ["node", "start-server.js"]

[nix]
channel = "stable-22_11"

[deployment]
run = ["node", "start-server.js"]

[languages]
nodejs = "20.x"

[env]
PORT = "3000"

[[ports]]
localPort = 3000
externalPort = 80