[languages.typescript]
pattern = "**/{*.ts,*.js,*.tsx,*.jsx}"
syntax = "typescript"

[languages.typescript.languageServer]
start = [ "typescript-language-server", "--stdio" ]

[env]
XDG_CONFIG_HOME = "/home/runner/.config"
PATH = "/home/runner/$REPL_SLUG/.config/npm/node_global/bin:/home/runner/$REPL_SLUG/node_modules/.bin"
npm_config_prefix = "/home/runner/$REPL_SLUG/.config/npm/node_global"
DATABASE_URL = "postgresql://classassgweb_user:zXufAtvnqY4cfi4Opa3SbomvEzllM4RJ@dpg-cvlojhngi27c73e8a6q0-a.oregon-postgres.render.com/classassgweb"
PGUSER = "classassgweb_user"
PGHOST = "dpg-cvlojhngi27c73e8a6q0-a.oregon-postgres.render.com"
PGPASSWORD = "zXufAtvnqY4cfi4Opa3SbomvEzllM4RJ"
PGDATABASE = "classassgweb"
PGPORT = "5432"
SERVICE_KEY = "sds-maverick-2024"

[gitHubImport]
requiredFiles = [".replit", "replit.nix", ".config", "package.json", "package-lock.json"]

[nix]
channel = "stable-22_11"

[deployment]
run = ["sh", "-c", "node StudentPerformanceTracker006/app.js"]
deploymentTarget = "cloudrun"

[packager]
language = "nodejs"

  [packager.features]
  packageSearch = true
  guessImports = true
  enabledForHosting = false

[unitTest]
language = "nodejs"

[debugger]
support = true

  [debugger.interactive]
  transport = "localhost:0"
  startCommand = [ "dap-node" ]

    [debugger.interactive.initializeMessage]
    command = "initialize"
    type = "request"

      [debugger.interactive.initializeMessage.arguments]
      clientID = "replit"
      clientName = "replit.com"
      columnsStartAt1 = true
      linesStartAt1 = true
      locale = "en-us"
      pathFormat = "path"
      supportsInvalidatedEvent = true
      supportsProgressReporting = true
      supportsRunInTerminalRequest = true
      supportsVariablePaging = true
      supportsVariableType = true

    [debugger.interactive.launchMessage]
    command = "launch"
    type = "request"
    
      [debugger.interactive.launchMessage.arguments]  
      args = []
      console = "externalTerminal"
      cwd = "."
      environment = []
      pauseForSourceMap = false
      program = "./StudentPerformanceTracker006/app.js"
      request = "launch"
      sourceMaps = true
      stopOnEntry = false
      type = "pwa-node"

[auth]
pageEnabled = false
buttonEnabled = false

[[ports]]
localPort = 3000
externalPort = 80